# Generated by Django 5.2.1 on 2026-05-20 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField()),
                ('dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cartao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cartao_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pix_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_dia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-closing_date', 'store__name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('VILA', 'Vila'), ('JACONE', 'Jaconé'), ('SAMPAIO', 'Sampaio')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(choices=[('ALUGUEL', 'Aluguel'), ('FORNECEDOR', 'Fornecedor'), ('MANUTENCAO', 'Manutenção'), ('SALARIO', 'Salário'), ('OUTROS', 'Outros')], max_length=30)),
                ('tipo_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO', 'Cartão'), ('TRANSFERENCIA', 'Transferência')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cash_closing.dailyclosing')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closings', to='cash_closing.store'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('LOJA', 'Loja')], default='LOJA', max_length=10)),
                ('authorized', models.BooleanField(default=False)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cash_closing.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailyclosing',
            constraint=models.UniqueConstraint(fields=('store', 'closing_date'), name='unique_store_closing_day'),
        ),
    ]
